// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfVD8Up3gTFSMaieoxDDuLEyQjc6nMlyc',
    appId: '1:380697858866:web:a1b0cd4d7fee57819dbd2b',
    messagingSenderId: '380697858866',
    projectId: 'autoservice-812e9',
    authDomain: 'autoservice-812e9.firebaseapp.com',
    storageBucket: 'autoservice-812e9.appspot.com',
    measurementId: 'G-BELV6DQ598',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtcEIsT2mSBZ4FbXZ7h7T4-Q_R6o5YIQA',
    appId: '1:380697858866:android:30918761d62058619dbd2b',
    messagingSenderId: '380697858866',
    projectId: 'autoservice-812e9',
    storageBucket: 'autoservice-812e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8CyrzHQ-GbwBiv973BsRLVr0-jCiazt4',
    appId: '1:380697858866:ios:2a10a6817c61502e9dbd2b',
    messagingSenderId: '380697858866',
    projectId: 'autoservice-812e9',
    storageBucket: 'autoservice-812e9.appspot.com',
    iosBundleId: 'com.example.autoServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8CyrzHQ-GbwBiv973BsRLVr0-jCiazt4',
    appId: '1:380697858866:ios:2a10a6817c61502e9dbd2b',
    messagingSenderId: '380697858866',
    projectId: 'autoservice-812e9',
    storageBucket: 'autoservice-812e9.appspot.com',
    iosBundleId: 'com.example.autoServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfVD8Up3gTFSMaieoxDDuLEyQjc6nMlyc',
    appId: '1:380697858866:web:7f1fff370350dc569dbd2b',
    messagingSenderId: '380697858866',
    projectId: 'autoservice-812e9',
    authDomain: 'autoservice-812e9.firebaseapp.com',
    storageBucket: 'autoservice-812e9.appspot.com',
    measurementId: 'G-YTDYMQEHZ1',
  );
}
